# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS aurora-jerry
COPY images/aurora-jerry/files /

# Base Image
FROM ghcr.io/ublue-os/aurora-dx:latest

RUN --mount=type=bind,from=aurora-jerry,source=/,target=/aurora-jerry \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /aurora-jerry/scripts/setup/10-repos.sh

RUN --mount=type=bind,from=aurora-jerry,source=/,target=/aurora-jerry \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /aurora-jerry/scripts/setup/10-packages.sh

RUN bootc container lint
