# Base Image
FROM ghcr.io/ublue-os/bazzite-nvidia-open:stable

# Copy files
COPY images/asteroid/files /files
COPY images/asteroid/files/system_files /

RUN --mount=type=bind,from=tmp/files,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /files/scripts/setup/10-repos.sh

RUN --mount=type=bind,from=files,source=/,target=/files \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /files/scripts/setup/10-packages.sh

# Finalize
#RUN --mount=type=bind,from=files,source=/,target=/files \
#    --mount=type=cache,dst=/var/cache \
#    --mount=type=cache,dst=/var/log \
#    --mount=type=tmpfs,dst=/tmp \
#    /files/scripts/final/build-initramfs.sh

RUN --mount=type=bind,from=files,source=/,target=/files \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /files/scripts/final/clean-up.sh

RUN rm -r /files

RUN bootc container lint
