FROM scratch AS asteroid_core
COPY images/asteroid/files /

# Base Image
FROM ghcr.io/ublue-os/silverblue-main:latest

RUN --mount=type=bind,from=asteroid_core,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asteroid_core/scripts/10-repos.sh

RUN --mount=type=bind,from=asteroid_core,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asteroid_core/scripts/10-packages.sh

RUN bootc container lint
